# ── Node.js ───────────────────────────────────────────────────
name: Pipeline Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      setup-node: true
      node-version: '20'
      install-command: npm ci
      run-tests: false
      lint-command: npm run lint
      build-command : npm run build
    
    secrets: inherit